/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './components/global/header.component.ngfactory';
import * as import2 from '../../app/components/global/header.component';
import * as import3 from '../../app/services/auth.service';
import * as import4 from 'angulartics2/dist/providers/ga/angulartics2-ga';
import * as import5 from 'angulartics2/dist/core/angulartics2';
import * as import6 from '@angular/router';
import * as import7 from './components/global/footer.component.ngfactory';
import * as import8 from '../../app/components/global/footer.component';
import * as import9 from '../../app/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-header',[[
        'class',
        'sticky'
      ]
    ],(null as any),(null as any),(null as any),import1.View_HeaderComponent_0,import1.RenderType_HeaderComponent)),
    import0.ɵdid(57344,(null as any),0,import2.HeaderComponent,[
      import3.Auth,
      import4.Angulartics2GoogleAnalytics,
      import5.Angulartics2
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),7,'main',[[
        'role',
        'main'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n	'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵeld(8388608,(null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(73728,(null as any),0,import6.RouterOutlet,[
      import6.RouterOutletMap,
      import0.ViewContainerRef,
      import0.ComponentFactoryResolver,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n	'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-footer',([] as any[]),(null as any),(null as any),(null as any),import7.View_FooterComponent_0,import7.RenderType_FooterComponent)),
    import0.ɵdid(57344,(null as any),0,import8.FooterComponent,[
      import4.Angulartics2GoogleAnalytics,
      import5.Angulartics2
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    ck(v,1,0);
    ck(v,14,0);
  },(null as any));
}
function View_AppComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import0.ɵdid(24576,(null as any),0,import9.AppComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import9.AppComponent> = import0.ɵccf('app-root',import9.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3RicC9Eb2N1bWVudHMvR2l0aHViL2N0dmMvdHJ1ZS10dWJlL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90YnAvRG9jdW1lbnRzL0dpdGh1Yi9jdHZjL3RydWUtdHViZS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy90YnAvRG9jdW1lbnRzL0dpdGh1Yi9jdHZjL3RydWUtdHViZS9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3RicC9Eb2N1bWVudHMvR2l0aHViL2N0dmMvdHJ1ZS10dWJlL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLWhlYWRlciBjbGFzcz1cInN0aWNreVwiID5cbjwvYXBwLWhlYWRlcj5cbjxtYWluIHJvbGU9XCJtYWluXCI+XG5cdDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cblx0XHQ8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG5cdDwvZGl2PlxuPC9tYWluPlxuPGFwcC1mb290ZXI+XG48L2FwcC1mb290ZXI+XG48IS0tIDxhcHAtZmVlZGJhY2s+XG48L2FwcC1mZWVkYmFjaz4gLS0+XG4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO2dCQUFBOzs7O0lBQUE7S0FBQTtJQUE0QjtJQUNmO01BQ2I7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFrQjtNQUNqQjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXVCO0lBQ3RCO2dCQUFBOzs7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUErQjtJQUMxQjtJQUNBO0lBQ1A7Z0JBQUE7OztJQUFBO0tBQUE7SUFBWTtJQUNDO0lBRU07OztJQVZuQjtJQU9BOzs7OztJQ1BBO2dCQUFBOzs7OyJ9
