/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from 'angular-confirmation-popover/dist/esm/src/confirmationPopover.module';
import * as import6 from '@angular/forms';
import * as import7 from '@angular/http';
import * as import8 from 'ngx-swiper-wrapper/dist/lib/swiper.module';
import * as import9 from 'angulartics2/dist/index';
import * as import10 from 'positioning/dist/positioning';
import * as import11 from 'angulartics2/dist/core/angulartics2';
import * as import12 from 'angulartics2/dist/providers/ga/angulartics2-ga';
import * as import13 from '../../app/services/auth.service';
import * as import14 from '../../app/services/data.service';
import * as import15 from '../../app/services/list.service';
import * as import16 from '../../app/components/content/listing/list.component';
import * as import17 from '../../app/components/content/listing/filter.component';
import * as import18 from '../../app/components/profile/profile.resolver';
import * as import19 from '../../app/services/user.service';
import * as import20 from '../node_modules/angular-confirmation-popover/dist/esm/src/confirmationPopoverWindow.component.ngfactory';
import * as import21 from './components/content/home/home.component.ngfactory';
import * as import22 from './components/content/listing/list.component.ngfactory';
import * as import23 from './components/content/calendar/calendar.component.ngfactory';
import * as import24 from './components/content/event/event.component.ngfactory';
import * as import25 from './components/content/item/item.component.ngfactory';
import * as import26 from './components/content/pages/item-page.component.ngfactory';
import * as import27 from './components/content/pages/page.component.ngfactory';
import * as import28 from './components/profile/profile.component.ngfactory';
import * as import29 from './components/profile/lists.component.ngfactory';
import * as import30 from './components/profile/list.component.ngfactory';
import * as import31 from './components/profile/rm-auth.component.ngfactory';
import * as import32 from './app.component.ngfactory';
import * as import33 from '../../app/components/content/home/home.component';
import * as import34 from '../../app/components/content/calendar/calendar.component';
import * as import35 from '../../app/components/content/event/event.component';
import * as import36 from '../../app/components/content/item/item.component';
import * as import37 from '../../app/components/content/pages/item-page.component';
import * as import38 from '../../app/components/content/pages/page.component';
import * as import39 from '../../app/components/profile/profile.component';
import * as import40 from '../../app/components/profile/lists.component';
import * as import41 from '../../app/components/profile/list.component';
import * as import42 from '../../app/components/profile/rm-auth.component';
import * as import43 from 'ngx-swiper-wrapper/dist/lib/swiper.interfaces';
import * as import44 from 'angular-confirmation-popover/dist/esm/src/confirmationPopoverOptions.provider';
import * as import45 from 'angular2-jwt/angular2-jwt';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:import1.RavenErrorHandler;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _ConfirmationPopoverModule_10:import5.ConfirmationPopoverModule;
  _ɵba_11:import6.ɵba;
  _FormsModule_12:import6.FormsModule;
  _HttpModule_13:import7.HttpModule;
  _ReactiveFormsModule_14:import6.ReactiveFormsModule;
  _ɵa_15:any;
  _UrlSerializer_16:import3.DefaultUrlSerializer;
  _RouterOutletMap_17:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_18:any;
  _LocationStrategy_19:any;
  _Location_20:import2.Location;
  _Compiler_21:import0.Compiler;
  _NgModuleFactoryLoader_22:import0.SystemJsNgModuleLoader;
  _ROUTES_23:any[];
  _Router_24:any;
  _RouterModule_25:import3.RouterModule;
  _SWIPER_GUARD_26:any;
  _SwiperModule_27:import8.SwiperModule;
  _ANGULARTICS2_FORROOT_GUARD_28:any;
  _Angulartics2Module_29:import9.Angulartics2Module;
  _AppModule_30:import1.AppModule;
  __LOCALE_ID_31:any;
  __NgLocalization_32:import2.NgLocaleLocalization;
  __APP_ID_33:any;
  __IterableDiffers_34:any;
  __KeyValueDiffers_35:any;
  __DomSanitizer_36:import4.ɵe;
  __Sanitizer_37:any;
  __HAMMER_GESTURE_CONFIG_38:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_39:any[];
  __EventManager_40:import4.EventManager;
  __ɵDomSharedStylesHost_41:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_42:import4.ɵDomRendererFactory2;
  __RendererFactory2_43:any;
  __ɵSharedStylesHost_44:any;
  __Testability_45:import0.Testability;
  __Meta_46:import4.Meta;
  __Title_47:import4.Title;
  __ɵi_48:import6.ɵi;
  __BrowserXhr_49:import7.BrowserXhr;
  __ResponseOptions_50:import7.BaseResponseOptions;
  __XSRFStrategy_51:any;
  __XHRBackend_52:import7.XHRBackend;
  __RequestOptions_53:import7.BaseRequestOptions;
  __Http_54:any;
  __FormBuilder_55:import6.FormBuilder;
  _USER_OPTIONS_56:any;
  __ConfirmationPopoverOptions_57:any;
  __Positioning_58:import10.Positioning;
  __ActivatedRoute_59:any;
  __NoPreloading_60:import3.NoPreloading;
  __PreloadingStrategy_61:any;
  __RouterPreloader_62:import3.RouterPreloader;
  __PreloadAllModules_63:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_64:any;
  __APP_BOOTSTRAP_LISTENER_65:any[];
  _SWIPER_CONFIG_66:any;
  __SwiperConfig_67:any;
  __Angulartics2_68:import11.Angulartics2;
  __Angulartics2GoogleAnalytics_69:import12.Angulartics2GoogleAnalytics;
  __AuthHttp_70:any;
  __Auth_71:import13.Auth;
  __DataService_72:import14.DataService;
  __ListService_73:import15.ListService;
  __ListingComponent_74:import16.ListingComponent;
  __ListFilterComponent_75:import17.ListFilterComponent;
  __LoggedInGuard_76:import13.LoggedInGuard;
  __ProfileResolver_77:import18.ProfileResolver;
  __UserService_78:import19.UserService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import20.ConfirmationPopoverWindowNgFactory,
      import21.HomeComponentNgFactory,
      import22.ListingComponentNgFactory,
      import23.CalendarComponentNgFactory,
      import24.EventComponentNgFactory,
      import25.ItemComponentNgFactory,
      import26.ItemPageComponentNgFactory,
      import27.PageComponentNgFactory,
      import28.ProfileComponentNgFactory,
      import29.UserListsComponentNgFactory,
      import30.UserListComponentNgFactory,
      import31.RmAuthComponentNgFactory,
      import32.AppComponentNgFactory
    ]
    ,[import32.AppComponentNgFactory]);
  }
  get _LOCALE_ID_31():any {
    if ((this.__LOCALE_ID_31 == null)) { (this.__LOCALE_ID_31 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_31;
  }
  get _NgLocalization_32():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_32 == null)) { (this.__NgLocalization_32 = new import2.NgLocaleLocalization(this._LOCALE_ID_31)); }
    return this.__NgLocalization_32;
  }
  get _APP_ID_33():any {
    if ((this.__APP_ID_33 == null)) { (this.__APP_ID_33 = import0.ɵg()); }
    return this.__APP_ID_33;
  }
  get _IterableDiffers_34():any {
    if ((this.__IterableDiffers_34 == null)) { (this.__IterableDiffers_34 = import0.ɵl()); }
    return this.__IterableDiffers_34;
  }
  get _KeyValueDiffers_35():any {
    if ((this.__KeyValueDiffers_35 == null)) { (this.__KeyValueDiffers_35 = import0.ɵm()); }
    return this.__KeyValueDiffers_35;
  }
  get _DomSanitizer_36():import4.ɵe {
    if ((this.__DomSanitizer_36 == null)) { (this.__DomSanitizer_36 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_36;
  }
  get _Sanitizer_37():any {
    if ((this.__Sanitizer_37 == null)) { (this.__Sanitizer_37 = this._DomSanitizer_36); }
    return this.__Sanitizer_37;
  }
  get _HAMMER_GESTURE_CONFIG_38():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_38 == null)) { (this.__HAMMER_GESTURE_CONFIG_38 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_38;
  }
  get _EVENT_MANAGER_PLUGINS_39():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_39 == null)) { (this.__EVENT_MANAGER_PLUGINS_39 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_38)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_39;
  }
  get _EventManager_40():import4.EventManager {
    if ((this.__EventManager_40 == null)) { (this.__EventManager_40 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_39,this.parent.get(import0.NgZone))); }
    return this.__EventManager_40;
  }
  get _ɵDomSharedStylesHost_41():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_41 == null)) { (this.__ɵDomSharedStylesHost_41 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_41;
  }
  get _ɵDomRendererFactory2_42():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_42 == null)) { (this.__ɵDomRendererFactory2_42 = new import4.ɵDomRendererFactory2(this._EventManager_40,this._ɵDomSharedStylesHost_41)); }
    return this.__ɵDomRendererFactory2_42;
  }
  get _RendererFactory2_43():any {
    if ((this.__RendererFactory2_43 == null)) { (this.__RendererFactory2_43 = this._ɵDomRendererFactory2_42); }
    return this.__RendererFactory2_43;
  }
  get _ɵSharedStylesHost_44():any {
    if ((this.__ɵSharedStylesHost_44 == null)) { (this.__ɵSharedStylesHost_44 = this._ɵDomSharedStylesHost_41); }
    return this.__ɵSharedStylesHost_44;
  }
  get _Testability_45():import0.Testability {
    if ((this.__Testability_45 == null)) { (this.__Testability_45 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_45;
  }
  get _Meta_46():import4.Meta {
    if ((this.__Meta_46 == null)) { (this.__Meta_46 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_46;
  }
  get _Title_47():import4.Title {
    if ((this.__Title_47 == null)) { (this.__Title_47 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_47;
  }
  get _ɵi_48():import6.ɵi {
    if ((this.__ɵi_48 == null)) { (this.__ɵi_48 = new import6.ɵi()); }
    return this.__ɵi_48;
  }
  get _BrowserXhr_49():import7.BrowserXhr {
    if ((this.__BrowserXhr_49 == null)) { (this.__BrowserXhr_49 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_49;
  }
  get _ResponseOptions_50():import7.BaseResponseOptions {
    if ((this.__ResponseOptions_50 == null)) { (this.__ResponseOptions_50 = new import7.BaseResponseOptions()); }
    return this.__ResponseOptions_50;
  }
  get _XSRFStrategy_51():any {
    if ((this.__XSRFStrategy_51 == null)) { (this.__XSRFStrategy_51 = import7.ɵb()); }
    return this.__XSRFStrategy_51;
  }
  get _XHRBackend_52():import7.XHRBackend {
    if ((this.__XHRBackend_52 == null)) { (this.__XHRBackend_52 = new import7.XHRBackend(this._BrowserXhr_49,this._ResponseOptions_50,this._XSRFStrategy_51)); }
    return this.__XHRBackend_52;
  }
  get _RequestOptions_53():import7.BaseRequestOptions {
    if ((this.__RequestOptions_53 == null)) { (this.__RequestOptions_53 = new import7.BaseRequestOptions()); }
    return this.__RequestOptions_53;
  }
  get _Http_54():any {
    if ((this.__Http_54 == null)) { (this.__Http_54 = import7.ɵc(this._XHRBackend_52,this._RequestOptions_53)); }
    return this.__Http_54;
  }
  get _FormBuilder_55():import6.FormBuilder {
    if ((this.__FormBuilder_55 == null)) { (this.__FormBuilder_55 = new import6.FormBuilder()); }
    return this.__FormBuilder_55;
  }
  get _ConfirmationPopoverOptions_57():any {
    if ((this.__ConfirmationPopoverOptions_57 == null)) { (this.__ConfirmationPopoverOptions_57 = import5.optionsFactory(this._USER_OPTIONS_56)); }
    return this.__ConfirmationPopoverOptions_57;
  }
  get _Positioning_58():import10.Positioning {
    if ((this.__Positioning_58 == null)) { (this.__Positioning_58 = new import10.Positioning()); }
    return this.__Positioning_58;
  }
  get _ActivatedRoute_59():any {
    if ((this.__ActivatedRoute_59 == null)) { (this.__ActivatedRoute_59 = import3.ɵf(this._Router_24)); }
    return this.__ActivatedRoute_59;
  }
  get _NoPreloading_60():import3.NoPreloading {
    if ((this.__NoPreloading_60 == null)) { (this.__NoPreloading_60 = new import3.NoPreloading()); }
    return this.__NoPreloading_60;
  }
  get _PreloadingStrategy_61():any {
    if ((this.__PreloadingStrategy_61 == null)) { (this.__PreloadingStrategy_61 = this._NoPreloading_60); }
    return this.__PreloadingStrategy_61;
  }
  get _RouterPreloader_62():import3.RouterPreloader {
    if ((this.__RouterPreloader_62 == null)) { (this.__RouterPreloader_62 = new import3.RouterPreloader(this._Router_24,this._NgModuleFactoryLoader_22,this._Compiler_21,this,this._PreloadingStrategy_61)); }
    return this.__RouterPreloader_62;
  }
  get _PreloadAllModules_63():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_63 == null)) { (this.__PreloadAllModules_63 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_63;
  }
  get _ROUTER_INITIALIZER_64():any {
    if ((this.__ROUTER_INITIALIZER_64 == null)) { (this.__ROUTER_INITIALIZER_64 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_64;
  }
  get _APP_BOOTSTRAP_LISTENER_65():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_65 == null)) { (this.__APP_BOOTSTRAP_LISTENER_65 = [this._ROUTER_INITIALIZER_64]); }
    return this.__APP_BOOTSTRAP_LISTENER_65;
  }
  get _SwiperConfig_67():any {
    if ((this.__SwiperConfig_67 == null)) { (this.__SwiperConfig_67 = import8.provideDefaultConfig(this._SWIPER_CONFIG_66)); }
    return this.__SwiperConfig_67;
  }
  get _Angulartics2_68():import11.Angulartics2 {
    if ((this.__Angulartics2_68 == null)) { (this.__Angulartics2_68 = new import11.Angulartics2(this._Location_20,this._Router_24)); }
    return this.__Angulartics2_68;
  }
  get _Angulartics2GoogleAnalytics_69():import12.Angulartics2GoogleAnalytics {
    if ((this.__Angulartics2GoogleAnalytics_69 == null)) { (this.__Angulartics2GoogleAnalytics_69 = new import12.Angulartics2GoogleAnalytics(this._Angulartics2_68)); }
    return this.__Angulartics2GoogleAnalytics_69;
  }
  get _AuthHttp_70():any {
    if ((this.__AuthHttp_70 == null)) { (this.__AuthHttp_70 = import13.authFactory(this._Http_54,this._RequestOptions_53)); }
    return this.__AuthHttp_70;
  }
  get _Auth_71():import13.Auth {
    if ((this.__Auth_71 == null)) { (this.__Auth_71 = new import13.Auth(this._ActivatedRoute_59,this._Router_24)); }
    return this.__Auth_71;
  }
  get _DataService_72():import14.DataService {
    if ((this.__DataService_72 == null)) { (this.__DataService_72 = new import14.DataService(this._Http_54,this._AuthHttp_70)); }
    return this.__DataService_72;
  }
  get _ListService_73():import15.ListService {
    if ((this.__ListService_73 == null)) { (this.__ListService_73 = new import15.ListService()); }
    return this.__ListService_73;
  }
  get _ListingComponent_74():import16.ListingComponent {
    if ((this.__ListingComponent_74 == null)) { (this.__ListingComponent_74 = new import16.ListingComponent(this._DataService_72,this._ListService_73,this._ActivatedRoute_59)); }
    return this.__ListingComponent_74;
  }
  get _ListFilterComponent_75():import17.ListFilterComponent {
    if ((this.__ListFilterComponent_75 == null)) { (this.__ListFilterComponent_75 = new import17.ListFilterComponent(this._ListService_73,this._ActivatedRoute_59,this._Router_24,this._ListingComponent_74,this._DataService_72,this._Location_20,this._FormBuilder_55,this._Angulartics2GoogleAnalytics_69,this._Angulartics2_68)); }
    return this.__ListFilterComponent_75;
  }
  get _LoggedInGuard_76():import13.LoggedInGuard {
    if ((this.__LoggedInGuard_76 == null)) { (this.__LoggedInGuard_76 = new import13.LoggedInGuard(this._Auth_71)); }
    return this.__LoggedInGuard_76;
  }
  get _ProfileResolver_77():import18.ProfileResolver {
    if ((this.__ProfileResolver_77 == null)) { (this.__ProfileResolver_77 = new import18.ProfileResolver(this._AuthHttp_70)); }
    return this.__ProfileResolver_77;
  }
  get _UserService_78():import19.UserService {
    if ((this.__UserService_78 == null)) { (this.__UserService_78 = new import19.UserService(this._AuthHttp_70)); }
    return this.__UserService_78;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = new import1.RavenErrorHandler();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ConfirmationPopoverModule_10 = new import5.ConfirmationPopoverModule();
    this._ɵba_11 = new import6.ɵba();
    this._FormsModule_12 = new import6.FormsModule();
    this._HttpModule_13 = new import7.HttpModule();
    this._ReactiveFormsModule_14 = new import6.ReactiveFormsModule();
    this._ɵa_15 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_16 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_17 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_18 = {};
    this._LocationStrategy_19 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_18);
    this._Location_20 = new import2.Location(this._LocationStrategy_19);
    this._Compiler_21 = new import0.Compiler();
    this._NgModuleFactoryLoader_22 = new import0.SystemJsNgModuleLoader(this._Compiler_21,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_23 = [[
        {
          path: '',
          component: import33.HomeComponent,
          data: {meta: {description: 'Description of the home page'}}
        }
        ,
        {
          path: 'list',
          component: import16.ListingComponent
        }
        ,
        {
          path: 'calendar',
          component: import34.CalendarComponent
        }
        ,
        {
          path: 'event/:id',
          component: import35.EventComponent
        }
        ,
        {
          path: 'item/:id',
          component: import36.ItemComponent
        }
        ,
        {
          path: 'film/:slug',
          component: import36.ItemComponent
        }
        ,
        {
          path: 'interactive/:slug',
          component: import36.ItemComponent
        }
        ,
        {
          path: 'audio/:slug',
          component: import36.ItemComponent
        }
        ,
        {
          path: 'node/:slug',
          component: import36.ItemComponent
        }
        ,
        {
          path: 'awards',
          component: import37.ItemPageComponent
        }
        ,
        {
          path: 'team',
          component: import37.ItemPageComponent
        }
        ,
        {
          path: 'partners',
          component: import37.ItemPageComponent
        }
        ,
        {
          path: 'terms-and-conditions',
          component: import38.PageComponent
        }
        ,
        {
          path: 'privacy-and-cookies',
          component: import38.PageComponent
        }
        ,
        {
          path: 'about',
          component: import38.PageComponent
        }
        ,
        {
          path: 'films',
          component: import16.ListingComponent,
            data: [{
              filter: 'typeFilm',
              type: 'content types'
            }
          ]
        }
        ,
        {
          path: 'lesson plans',
          component: import16.ListingComponent,
            data: [{
              filter: 'typeLesson',
              type: 'content types'
            }
          ]
        }
        ,
        {
          path: 'assembly scripts',
          component: import16.ListingComponent,
            data: [{
              filter: 'typeAssembly',
              type: 'content types'
            }
          ]
        }
        ,
        {
          path: 'interactive',
          component: import16.ListingComponent,
            data: [{
              filter: 'typeInteractive',
              type: 'content types'
            }
          ]
        }
        ,
        {
          path: 'me',
          component: import39.ProfileComponent,
          canActivate: [import13.LoggedInGuard],
          resolve: {profile: import18.ProfileResolver}
        }
        ,
        {
          path: 'me/lists',
          component: import40.UserListsComponent,
          canActivate: [import13.LoggedInGuard],
          resolve: {profile: import18.ProfileResolver}
        }
        ,
        {
          path: 'me/list/:id',
          component: import41.UserListComponent,
          canActivate: [import13.LoggedInGuard],
          resolve: {profile: import18.ProfileResolver}
        }
        ,
        {
          path: 'rm/callback',
          component: import42.RmAuthComponent
        }

      ]
    ];
    this._Router_24 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_16,this._RouterOutletMap_17,this._Location_20,this,this._NgModuleFactoryLoader_22,this._Compiler_21,this._ROUTES_23,this._ROUTER_CONFIGURATION_18,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_25 = new import3.RouterModule(this._ɵa_15,this._Router_24);
    this._SWIPER_GUARD_26 = import8.provideForRootGuard(this.parent.get(import43.SwiperConfig,(null as any)));
    this._SwiperModule_27 = new import8.SwiperModule(this._SWIPER_GUARD_26);
    this._ANGULARTICS2_FORROOT_GUARD_28 = import9.provideForRootGuard(this.parent.get(import11.Angulartics2,(null as any)));
    this._Angulartics2Module_29 = new import9.Angulartics2Module(this._ANGULARTICS2_FORROOT_GUARD_28);
    this._AppModule_30 = new import1.AppModule();
    this._USER_OPTIONS_56 = {confirmButtonType: 'danger'};
    this._SWIPER_CONFIG_66 = {
      pagination: '.swiper-pagination',
      slidesPerView: 1,
      paginationClickable: true,
      spaceBetween: 0,
      loop: false,
      autoplay: 5000
    }
    ;
    return this._AppModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.ConfirmationPopoverModule)) { return this._ConfirmationPopoverModule_10; }
    if ((token === import6.ɵba)) { return this._ɵba_11; }
    if ((token === import6.FormsModule)) { return this._FormsModule_12; }
    if ((token === import7.HttpModule)) { return this._HttpModule_13; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_14; }
    if ((token === import3.ɵa)) { return this._ɵa_15; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_16; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_17; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_18; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_19; }
    if ((token === import2.Location)) { return this._Location_20; }
    if ((token === import0.Compiler)) { return this._Compiler_21; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_22; }
    if ((token === import3.ROUTES)) { return this._ROUTES_23; }
    if ((token === import3.Router)) { return this._Router_24; }
    if ((token === import3.RouterModule)) { return this._RouterModule_25; }
    if ((token === import8.SWIPER_GUARD)) { return this._SWIPER_GUARD_26; }
    if ((token === import8.SwiperModule)) { return this._SwiperModule_27; }
    if ((token === import9.ANGULARTICS2_FORROOT_GUARD)) { return this._ANGULARTICS2_FORROOT_GUARD_28; }
    if ((token === import9.Angulartics2Module)) { return this._Angulartics2Module_29; }
    if ((token === import1.AppModule)) { return this._AppModule_30; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_31; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_32; }
    if ((token === import0.APP_ID)) { return this._APP_ID_33; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_34; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_35; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_36; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_37; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_38; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_39; }
    if ((token === import4.EventManager)) { return this._EventManager_40; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_41; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_42; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_43; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_44; }
    if ((token === import0.Testability)) { return this._Testability_45; }
    if ((token === import4.Meta)) { return this._Meta_46; }
    if ((token === import4.Title)) { return this._Title_47; }
    if ((token === import6.ɵi)) { return this._ɵi_48; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_49; }
    if ((token === import7.ResponseOptions)) { return this._ResponseOptions_50; }
    if ((token === import7.XSRFStrategy)) { return this._XSRFStrategy_51; }
    if ((token === import7.XHRBackend)) { return this._XHRBackend_52; }
    if ((token === import7.RequestOptions)) { return this._RequestOptions_53; }
    if ((token === import7.Http)) { return this._Http_54; }
    if ((token === import6.FormBuilder)) { return this._FormBuilder_55; }
    if ((token === import5.USER_OPTIONS)) { return this._USER_OPTIONS_56; }
    if ((token === import44.ConfirmationPopoverOptions)) { return this._ConfirmationPopoverOptions_57; }
    if ((token === import10.Positioning)) { return this._Positioning_58; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_59; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_60; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_61; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_62; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_63; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_64; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_65; }
    if ((token === import8.SWIPER_CONFIG)) { return this._SWIPER_CONFIG_66; }
    if ((token === import43.SwiperConfig)) { return this._SwiperConfig_67; }
    if ((token === import11.Angulartics2)) { return this._Angulartics2_68; }
    if ((token === import12.Angulartics2GoogleAnalytics)) { return this._Angulartics2GoogleAnalytics_69; }
    if ((token === import45.AuthHttp)) { return this._AuthHttp_70; }
    if ((token === import13.Auth)) { return this._Auth_71; }
    if ((token === import14.DataService)) { return this._DataService_72; }
    if ((token === import15.ListService)) { return this._ListService_73; }
    if ((token === import16.ListingComponent)) { return this._ListingComponent_74; }
    if ((token === import17.ListFilterComponent)) { return this._ListFilterComponent_75; }
    if ((token === import13.LoggedInGuard)) { return this._LoggedInGuard_76; }
    if ((token === import18.ProfileResolver)) { return this._ProfileResolver_77; }
    if ((token === import19.UserService)) { return this._UserService_78; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_41 && this._ɵDomSharedStylesHost_41.ngOnDestroy());
    (this.__RouterPreloader_62 && this._RouterPreloader_62.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3RicC9Eb2N1bWVudHMvR2l0aHViL2N0dmMvdHJ1ZS10dWJlL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90YnAvRG9jdW1lbnRzL0dpdGh1Yi9jdHZjL3RydWUtdHViZS9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
