/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/shared/partners-carousel.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../app/services/data.service';
import * as import9 from 'angulartics2/dist/providers/ga/angulartics2-ga';
import * as import10 from 'angulartics2/dist/core/angulartics2';
import * as import11 from '../../../node_modules/angulartics2/dist/core/angulartics2On.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import16 from 'angulartics2/dist/core/angulartics2On';
import * as import17 from '@angular/core/src/security';
import * as import18 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import19 from 'angular2-swiper-wrapper/dist/lib/swiper.component';
import * as import20 from '../../../node_modules/angular2-swiper-wrapper/dist/lib/swiper.component.ngfactory';
import * as import21 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import22 from '@angular/router/src/router';
import * as import23 from '@angular/router/src/router_state';
import * as import24 from '@angular/common/src/location/location_strategy';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import27 from 'angular2-swiper-wrapper/dist/lib/swiper.interfaces';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from '@angular/router/src/directives/router_link';
import * as import31 from '@angular/common/src/directives/ng_for';
export class Wrapper_PartnersCarouselComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PartnersCarouselComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.PartnersCarouselComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PartnersCarouselComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PartnersCarouselComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PartnersCarouselComponent>;
  _PartnersCarouselComponent_0_3:Wrapper_PartnersCarouselComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PartnersCarouselComponent_Host0,renderType_PartnersCarouselComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-partners-carousel',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PartnersCarouselComponent0(this.viewUtils,this,0,this._el_0);
    this._PartnersCarouselComponent_0_3 = new Wrapper_PartnersCarouselComponent(this.injectorGet(import8.DataService,this.parentIndex),this.injectorGet(import9.Angulartics2GoogleAnalytics,this.parentIndex),this.injectorGet(import10.Angulartics2,this.parentIndex));
    this.compView_0.create(this._PartnersCarouselComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PartnersCarouselComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PartnersCarouselComponent) && (0 === requestNodeIndex))) { return this._PartnersCarouselComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PartnersCarouselComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PartnersCarouselComponentNgFactory:import7.ComponentFactory<import0.PartnersCarouselComponent> = new import7.ComponentFactory<import0.PartnersCarouselComponent>('app-partners-carousel',View_PartnersCarouselComponent_Host0,import0.PartnersCarouselComponent);
const styles_PartnersCarouselComponent:any[] = ([] as any[]);
class View_PartnersCarouselComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Angulartics2On_2_3:import11.Wrapper_Angulartics2On;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_8:any;
  _map_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_PartnersCarouselComponent1,renderType_PartnersCarouselComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_8 = import13.UNINITIALIZED;
    this._map_9 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {label: p0};
    });
    this._expr_10 = import13.UNINITIALIZED;
    this._expr_11 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','swiper-slide'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray8(6,'angulartics2On','click','angularticsCategory','Partner Carousel','angularticsEvent','Navigate'),(null as any));
    this._Angulartics2On_2_3 = new import11.Wrapper_Angulartics2On(new import14.ElementRef(this._el_2),this.parentView.parentView.injectorGet(import10.Angulartics2,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import15.EventManager,this.parentView.parentIndex));
    this._text_3 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.Angulartics2On) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Angulartics2On_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = 'click';
    this._Angulartics2On_2_3.check_angulartics2On(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = 'Navigate';
    this._Angulartics2On_2_3.check_angularticsEvent(currVal_2_0_1,throwOnChange,false);
    const currVal_2_0_2:any = 'Partner Carousel';
    this._Angulartics2On_2_3.check_angularticsCategory(currVal_2_0_2,throwOnChange,false);
    const currVal_2_0_3:any = this._map_9(this.context.$implicit.link);
    this._Angulartics2On_2_3.check_angularticsProperties(currVal_2_0_3,throwOnChange,false);
    this._Angulartics2On_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Angulartics2On_2_3.context.ngAfterContentInit(); } }
    const currVal_8:any = import3.inlineInterpolate(1,'',this.context.$implicit.link,'');
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    const currVal_10:any = import3.inlineInterpolate(1,'',this.context.$implicit.image,'');
    if (import3.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_10));
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import3.inlineInterpolate(1,'',this.context.$implicit.image.alt,'');
    if (import3.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_4,'alt',currVal_11);
      this._expr_11 = currVal_11;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_PartnersCarouselComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_PartnersCarouselComponent,{});
export class View_PartnersCarouselComponent0 extends import1.AppView<import0.PartnersCarouselComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import18.Wrapper_RouterLinkWithHref;
  _Angulartics2On_9_4:import11.Wrapper_Angulartics2On;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  compView_13:import1.AppView<import19.SwiperComponent>;
  _SwiperComponent_13_3:import20.Wrapper_SwiperComponent;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import12.ViewContainer;
  _TemplateRef_15_5:any;
  _NgFor_15_6:import21.Wrapper_NgFor;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _map_27:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PartnersCarouselComponent0,renderType_PartnersCarouselComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_27 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {label: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','partners-carousel'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','partners-carousel-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Our Partners',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'a',new import3.InlineArray16(10,'angulartics2On','click','angularticsCategory','Partner Carousel','angularticsEvent','Navigate','class','text-link','href','#'),(null as any));
    this._RouterLinkWithHref_9_3 = new import18.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import22.Router,this.parentIndex),this.parentView.injectorGet(import23.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import24.LocationStrategy,this.parentIndex));
    this._Angulartics2On_9_4 = new import11.Wrapper_Angulartics2On(new import14.ElementRef(this._el_9),this.parentView.injectorGet(import10.Angulartics2,this.parentIndex),this.parentView.injectorGet(import15.EventManager,this.parentIndex));
    this._text_10 = this.renderer.createText(this._el_9,'Work with us',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n	',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_2,'swiper',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_13 = new import20.View_SwiperComponent0(this.viewUtils,this,13,this._el_13);
    this._SwiperComponent_13_3 = new import20.Wrapper_SwiperComponent(this.parentView.injectorGet(import25.NgZone,this.parentIndex),new import14.ElementRef(this._el_13),this.parentView.injectorGet(import26.KeyValueDiffers,this.parentIndex),this.parentView.injectorGet(import27.SwiperConfig,this.parentIndex,(null as any)));
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_15 = new import12.ViewContainer(15,13,this,this._anchor_15);
    this._TemplateRef_15_5 = new import28.TemplateRef_(this,15,this._anchor_15);
    this._NgFor_15_6 = new import21.Wrapper_NgFor(this._vc_15.vcRef,this._TemplateRef_15_5,this.parentView.injectorGet(import29.IterableDiffers,this.parentIndex),this.ref);
    this._text_16 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_13.create(this._SwiperComponent_13_3.context);
    this._text_17 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3.context; }
    if (((token === import16.Angulartics2On) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Angulartics2On_9_4.context; }
    if (((token === import28.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import31.NgFor) && (15 === requestNodeIndex))) { return this._NgFor_15_6.context; }
    if (((token === import19.SwiperComponent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._SwiperComponent_13_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_9_0_0:any = '/partners';
    this._RouterLinkWithHref_9_3.check_routerLink(currVal_9_0_0,throwOnChange,false);
    this._RouterLinkWithHref_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = 'click';
    this._Angulartics2On_9_4.check_angulartics2On(currVal_9_1_0,throwOnChange,false);
    const currVal_9_1_1:any = 'Navigate';
    this._Angulartics2On_9_4.check_angularticsEvent(currVal_9_1_1,throwOnChange,false);
    const currVal_9_1_2:any = 'Partner Carousel';
    this._Angulartics2On_9_4.check_angularticsCategory(currVal_9_1_2,throwOnChange,false);
    const currVal_9_1_3:any = this._map_27('Work with us');
    this._Angulartics2On_9_4.check_angularticsProperties(currVal_9_1_3,throwOnChange,false);
    this._Angulartics2On_9_4.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_13_0_0:any = this.context.carouselConfig;
    this._SwiperComponent_13_3.check_config(currVal_13_0_0,throwOnChange,false);
    this._SwiperComponent_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_15_0_0:any = this.context.slides;
    this._NgFor_15_6.check_ngForOf(currVal_15_0_0,throwOnChange,false);
    this._NgFor_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Angulartics2On_9_4.context.ngAfterContentInit(); } }
    this._RouterLinkWithHref_9_3.checkHost(this,this,this._el_9,throwOnChange);
    this._SwiperComponent_13_3.checkHost(this,this.compView_13,this._el_13,throwOnChange);
    this.compView_13.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_15.destroyNestedViews();
    this.compView_13.destroy();
    this._RouterLinkWithHref_9_3.ngOnDestroy();
    this._SwiperComponent_13_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 13) && (ngContentIndex == 0))) {
      cb(this._text_14,ctx);
      cb(this._vc_15.nativeElement,ctx);
      this._vc_15.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_16,ctx);
    }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 15)) { return new View_PartnersCarouselComponent1(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_9_3.handleEvent(eventName,$event) && result);
    return result;
  }
}