/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../app/components/content/item/audio.component';
const styles_AudioComponent:any[] = ([] as any[]);
export const RenderType_AudioComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AudioComponent,
  data: {}
}
);
export function View_AudioComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{player: 0}),
    (l()(),import0.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'player',
        1
      ]

    ]
    ,(null as any),7,'audio',[
      [
        'class',
        'video-js vjs-default-skin vjs-big-play-centered'
      ]
      ,
      [
        'controls',
        ''
      ]
      ,
      [
        'id',
        'player'
      ]
      ,
      [
        'preload',
        'auto'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '\n<source src="',
      '" type="audio/mp3"">\n  '
    ]
    )),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'p',[[
        'class',
        'vjs-no-js'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    To listen to this audio please enable JavaScript, and consider upgrading to a web browser that\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'a',[
      [
        'href',
        'http://videojs.com/html5-video-support/'
      ]
      ,
      [
        'target',
        '_blank'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['supports HTML5 audio'])),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.AudioComponent = v.component;
    const currVal_0:any = co.embed.source;
    ck(v,2,0,currVal_0);
  });
}
function View_AudioComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-audio-player',([] as any[]),(null as any),(null as any),(null as any),View_AudioComponent_0,RenderType_AudioComponent)),
    import0.ɵdid(122880,(null as any),0,import1.AudioComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AudioComponentNgFactory:import0.ComponentFactory<import1.AudioComponent> = import0.ɵccf('app-audio-player',import1.AudioComponent,View_AudioComponent_Host_0,{
  embed: 'embed',
  embeddedContent: 'embeddedContent',
  activeTab: 'activeTab',
  subtitles: 'subtitles'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3RicC9Eb2N1bWVudHMvR2l0aHViL2N0dmMvdHJ1ZS10dWJlL3NyYy9hcHAvY29tcG9uZW50cy9jb250ZW50L2l0ZW0vYXVkaW8uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3RicC9Eb2N1bWVudHMvR2l0aHViL2N0dmMvdHJ1ZS10dWJlL3NyYy9hcHAvY29tcG9uZW50cy9jb250ZW50L2l0ZW0vYXVkaW8uY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvdGJwL0RvY3VtZW50cy9HaXRodWIvY3R2Yy90cnVlLXR1YmUvc3JjL2FwcC9jb21wb25lbnRzL2NvbnRlbnQvaXRlbS9hdWRpby5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3RicC9Eb2N1bWVudHMvR2l0aHViL2N0dmMvdHJ1ZS10dWJlL3NyYy9hcHAvY29tcG9uZW50cy9jb250ZW50L2l0ZW0vYXVkaW8uY29tcG9uZW50LnRzLkF1ZGlvQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGF1ZGlvICNwbGF5ZXIgaWQ9XCJwbGF5ZXJcIiBjbGFzcz1cInZpZGVvLWpzIHZqcy1kZWZhdWx0LXNraW4gdmpzLWJpZy1wbGF5LWNlbnRlcmVkXCIgY29udHJvbHMgcHJlbG9hZD1cImF1dG9cIj5cbjxzb3VyY2Ugc3JjPVwie3tlbWJlZC5zb3VyY2V9fVwiIHR5cGU9XCJhdWRpby9tcDNcIlwiPlxuICA8cCBjbGFzcz1cInZqcy1uby1qc1wiPlxuICAgIFRvIGxpc3RlbiB0byB0aGlzIGF1ZGlvIHBsZWFzZSBlbmFibGUgSmF2YVNjcmlwdCwgYW5kIGNvbnNpZGVyIHVwZ3JhZGluZyB0byBhIHdlYiBicm93c2VyIHRoYXRcbiAgICA8YSBocmVmPVwiaHR0cDovL3ZpZGVvanMuY29tL2h0bWw1LXZpZGVvLXN1cHBvcnQvXCIgdGFyZ2V0PVwiX2JsYW5rXCI+c3VwcG9ydHMgSFRNTDUgYXVkaW88L2E+XG4gIDwvcD5cbjwvYXVkaW8+XG4iLCI8YXBwLWF1ZGlvLXBsYXllcj48L2FwcC1hdWRpby1wbGF5ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQTJHO01BQUE7TUFBQTtJQUFBO0lBQUE7TUFFekc7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFxQjtJQUVuQjtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBa0U7SUFBd0I7SUFDeEY7SUFDRTs7OztJQU5tRztJQUFBOzs7OztJQ0EzRztnQkFBQTs7O0lBQUE7Ozs7Ozs7OzsifQ==
